#!/bin/sh
mysqldump --add-drop-table --no-data db54010_envirovote -h internal-db.s54010.gridserver.com -u db54010_evote -pas3092j30ajwer3 | grep DROP | mysql db54010_envirovote -h internal-db.s54010.gridserver.com -u db54010_evote -pas3092j30ajwer3
